dist: trusty
sudo: false
language: node_js
node_js:
- 10.15.3
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - "./node_modules"
before_script:
- npm run build
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: GuVgAXvt/13rHhLXLprb+R85iLrdllhHkp1lzBRifLrkElEWBOlKywuStpdhP+IcGr900wdbp1zkb/AXhSqJaNCLAKj5plwjbsL7oHD/VEphHE+pC6U0bBZuEoJfa/bckHEv6vuwHRzbFiisZijxcumjJqSUAK0qqm/G0+92lZRJA9h5ZP7R+bVfMlnDM/AkEtvFREjOSMN5jQx7OO+YrvxPlluIp1CGYX9lUNzFH7z5Keu16VWShc1R3mWYSK7QusANqlB9M8noP6zEEyL5Pr3NRdX7csnFSR76jJ48gnbcWR2OAtaBeFqSrZ+Kmp17NICrvaEYSY2nGKNECE9GvLjpp6SBtyyEPu9pLCjJ+H293IjRl3Ympv4S9MURflQLxMZIYIZgC5fIfUD2K2NcJsisaqyOx6C3GZPEYccG/P2NFlFuw9p2eJEMyFr7YIzuJEiAE/VsIvpkKJngBYxlrznMRstEgjZp1xwMC+hhhgcWiOmLuxPNoTFZ9G2mSbp3MBhyB6sGgk6rmhQd9wVi4DmS2gJevqCaLYOknisPwKwgr20HRMtSUpEzXu/t8Mly/keG5UDtlkwu0jdIP87+7/uXLG3zFU2lZeoLOrWc31V+j/B+LnGTMrv/t7Eb4B+OTAIpKEJx6NvZGdGnDaEP5B9lfpmeIAfspJDGgw/+yDA=
  app: runfindr-server-test
  on:
    repo: richardwkirk/runfindr-server
