dist: trusty
sudo: false
language: node_js
node_js:
- 10.15.3
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - "./node_modules"
before_script:
- npm run build
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: ytgedjTVe4hVoNc75SdDbdp/I3tcPOVNbvM0ZpfE3399OTBgPg5zaFhc1isu6eUA5vEijweOlIgrdvzzQWBKp+CBBXxax24+XCKBfsiltOC3he4Op16TetWiWB3xKV/hgkKpy2Nus7mRDXiiXBrPFMWh9nKPdjkxDqp9WT5HkVU/+Dcyrzpn+xW1yNp3kbjweGvoj0JpaVjGiHzYqW6RTEks/uUCx3guWrr2tk0UcotyqsntFCGIXtWtTPslUAywOSKWUP39+iTjeBAJ0uBEEp/kWofp4HXl/s0puAUBZNopLs8TcweOMreQAPpq/1OWKVLQv99lpeQktrlhWsTlHTQ1i1w8kh9r5vatVW1L4OFqiEx7t/stp7I4glyWhCVo32vGv+/gz6lovIePBLraRxKb8ShuneOvw7QT+BD+KUf3Koh+a4i0pTQPqW6C1uy7p7lFIbbW41BIt+sX005vKQ4Mcz4GxYd6tMLMW2awZGJrJCYrwM6CvbS3ZBEfAHxWRsc+cCBw09Z+eMSyqvfcZGtKRhI5bgfhiN/EA9Et1h3mcwApfzZPrsyz3I7ncpZ6mixq+Y0pBdA9oBsjLOa3lgrHRFeVR+y1JsBFPd9tN1iQWv+JsRo13LWlbgExZzt1/dSPhPKbRvlMROz0N3DN6sY0e3ReoFNj5ECetDSoQcY=
  app:
    master: runfindr-server-test
    production: runfindr-server
