dist: trusty
sudo: false
language: node_js
node_js:
- 10.15.3
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - "./node_modules"
before_script:
- npm run build
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: bx12s0czXjF14Je/acA1aO0bnPDRZfjZOA5QIwxqlsW0/GuvalKaxvw9ZIxbwvPQKe3+QMyAvg2uu/ub7PGfDiTv5mB4KpNo7xRVP78fe4uXe5wk7mIrAjL4E1LkrcSsGMJvDA4tv18dbR/bWieNX21uzoqJzHzWpnpdyV2cnTivlA8evkGuKPMmPsTVolWlDsCY64ce5FXeWxY36oSNC3BXF75eilcad6Z3MyK6wIF1c1kSYwsQrEuN3P4cQTxuSFmSsa6wXIlPuKHP1g8DzTaPtCLblT4ueNjuhf9+slcfg67WTJhJMDmDQNxlxigcQqUKneuBGZm2/xdddQu0Iq0/UW2ais8Lu+xwgE34UkpOikiBLZN829fN1U74nQTgkEPPbC+Q0hO3DAtX0cbBWbGlVfS7cinsgg311Rnyupfv5kijjmTc85D4YdBs0TWG+BYzdDhgDPwnzyyTOE/v3PXfDZWk7oBlbR6Zzgh5BitgCtx0P/CXW8n9gGWSMS0qH0AgWg61PRrOTH35JiV0v9CUHloYKgC+rV8jFHOfzjnDUYTSQH/Qd020ycC0d5wxA7Sn8uuivxZUu9U80ZCkCRg/ANFBLGyIOhku52IH3S1hM8OYglLqBU9mupY/Je1W8AIN9HY9rIjM98wNJ1K1pLnF4NVMIm32V80vqrvaGaQ=
  app: runfindr-server-test
  on:
    repo: richardwkirk/runfindr-server
env:
  global:
    secure: qK270Lp12+px3izIATrtV4c9Ap8kKjuPDHmWjDOEJhJZSDuQa9nQCOmETYoWGlcSm+olXOhGKDa98UOTWyTKT6ckb4RkULsORyIufbxukLRect9p2Sx9ib07gmxGF7+DIYnZ9D8riOMpy8dbU4oJmID9612fm9slobQH2w6KjJL039aLXLBIz40Z8vdziRpnsRl6tzeh/+tDnM/VSulAoYfoQAkHdXk12I4M/iC6YqKblIKLDsN0UQfXUwFFig+UoUhHLWp6NeAeVsBwdEvT7SIVqhTfMrNCSEBCJjzLdBpxnqIgs8u6CB5pLImB5+YR6U3q+CTitjvZK0tMn8BLcE3k9XjetQ9Q4dUibJIl5P5hMoxiojm1FDiIvLcEvtK5TNLcQmKKE1g80MbZf2nzrcUTftgECEV8evILxIdb162CAv06WPF+6ViXS60sX6aFLwq7v39Clj2GZb3F9kYuZcWFLC++QaETvOchboU369JeP4MKJ+kCXLlCQePjjbIZsRN+UYrFGVqBKbhtuvIOhbmtdMbj1r9xz3v7jpqwALEcWgnfJMEVih6lcSmLL+2iU91FX5NBtkI2Q9Kwk1oDZTCpMWG3DVPnI2MK3EnQ6u0vh9WSnu9hcnh3CMPqL91N3yXtoLIueUD02y9U5/fguW/BjkUBi0WOc8d8xu+cqEo=
